/// Flutter icons AuraIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AuraIcons
///      fonts:
///       - asset: fonts/AuraIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AuraIcons {
  AuraIcons._();

  static const _kFontFam = 'AuraIcons';
  static const String? _kFontPkg = null;

  static const IconData Android_back = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData User_cutout = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Decrease = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData NPI = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Transaction = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Darkweb = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iOS_back = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Credit_monitoring = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Close = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Circle = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Check_circle = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Pagination = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Loyalty_card = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Flag = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Notifications = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData User_group = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Notifications_cutout = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Twisty_closed = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Twisty_open = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData User = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Moon = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Mobile = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Plus = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Help = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData List = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Key = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData More = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Settings = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Erase = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Call = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Checkbox_filled = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Eye_opened = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Eye_closed = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Check = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Medal = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Login = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Unink = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Link = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Plan = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Address = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Wallet = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Credit_card = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Credit_report = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Present = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Contacts = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Chart = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Cash = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData More_options = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Unsecured = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Archive = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Increase = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Archived = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Dark_web = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Question = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Positive = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData User_minor = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Arrow_left = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Arrow_right = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData User_adult = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bell_settings = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Dollar_circle = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Radio_active = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Arrow_down_right = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bus = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Arrow_up_left = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Refresh = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Timer = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Edit = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData WiFi = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Remove_user = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Gavel = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Filters = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Withdraw_email = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Clock = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Delete = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Data_broker = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Credit_freeze = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Checkbox_empty = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Chevron_down = IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Shield_check = IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Speedometer = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Negative = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Alert = IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Credit_unlock = IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_change = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_add = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_plus_add = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_add = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_circle = IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_check = IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id = IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData malware = IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData score_down = IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData score_up = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_cross = IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_duplicate = IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unarchive = IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_check = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_search = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_inactive = IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_document_police = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_document_user = IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_added = IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_removed = IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ball = IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainment = IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_place = IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent = IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_account_pending = IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_account_verified = IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_ned_acount_holder = IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_new_signer = IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_check = IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult = IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threads_resolved = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_protection = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tracker = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_number = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indeterminate = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Password_history = IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_btn = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_btn = IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_remove = IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
